import frappe
from frappe.model.document import Document


class ProjectBudgetRevision(Document):
	def validate(self):
		if not self.is_new() or not self.flags.from_project_workspace:
			frappe.throw("Project budget revisions are generated by the system and cannot be edited.")
