import frappe
from frappe import _
from frappe.model.document import Document


class EmployeeAdvanceFreezeEvent(Document):
	def validate(self):
		from volunteering.volunteering.advance_freeze import freeze_mutation_allowed

		if not self.is_new() or not freeze_mutation_allowed():
			frappe.throw(
				_("Advance freeze history is generated by the Team workflow and cannot be edited."),
				frappe.PermissionError,
			)

	def on_trash(self):
		frappe.throw(
			_("Advance freeze history is retained for audit and cannot be deleted."),
			frappe.PermissionError,
		)
